language: php
php:
  - '7.4snapshot'

addons:
  postgresql: "10"

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=ussr_poker
    - DB_USER=ussr_poker
    - DB_PASS=secret
    - DB_PORT=5432

before_install:
  - psql -c "CREATE DATABASE ussr_poker;" -U postgres -p ${DB_PORT}
  - psql -c "CREATE USER ussr_poker WITH PASSWORD 'secret';" -U postgres -p ${DB_PORT}

cache:
  directories:
    - /home/travis/swoole-src
    - /home/travis/.composer

install:
  - bash travis_swoole.sh
  - composer install
  - php migrate.php

test:
  - vendor/bin/phpunit
