dist: bionic
language: php
php:
  - '7.4snapshot'

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

env:
  global:
    - PG_PORT=5433
    - DB_HOST=127.0.0.1
    - DB_NAME=ussr_poker
    - DB_USER=ussr_poker
    - DB_PASS=secret
    - DB_PORT=5433

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main
  - sleep 1
  - psql -c "CREATE DATABASE ussr_poker;" -U postgres -p ${PG_PORT}
  - psql -c "CREATE USER ussr_poker WITH PASSWORD 'secret';" -U postgres -p ${PG_PORT}

install:
  - git clone https://github.com/swoole/swoole-src.git
  - cd swoole-src
  - phpize
  - ./configure --enable-sockets
  - make -j 4 && make install
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ../
  - phpenv config-rm xdebug.ini
  - composer install

test:
  - php migrate.php
  - vendor/bin/phpunit
