language: php
php:
  - '7.4snapshot'

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

env:
  global:
    - PG_PORT=5433
    - DB_HOST=postgres
    - DB_NAME=ussr_poker
    - DB_USER=ussr_poker
    - DB_PASS=secret
    - DB_PORT=5433

before_install:
  - sudo systemctl status postgresql@11-main
  - psql -c "CREATE DATABASE ussr_poker;" -U postgres
  - psql -c "CREATE USER ussr_poker WITH PASSWORD 'secret';" -U postgres

install:
  - git clone https://github.com/swoole/swoole-src.git
  - cd swoole-src
  - phpize
  - ./configure --enable-sockets
  - make -j 4 && make install
  - cd ../
  - rm -rf swoole-src
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php --ri swoole
  - composer install

test:
  - php migrate.php
  - vendor/bin/phpunit
