language: php
php:
  - '7.4snapshot'

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

services:
  - postgresql

env:
  global:
    - PG_PORT=5433
    - DB_HOST=postgres
    - DB_NAME=ussr_poker
    - DB_USER=ussr_poker
    - DB_PASS=secret
    - DB_PORT=5433

before_script:
  - psql -c "CREATE DATABASE ussr_poker;" -U postgres
  - psql -c "CREATE USER ussr_poker WITH PASSWORD 'secret';" -U postgres

install:
  - printf "\n" | pecl install swoole
  - composer install

test:
  - php migrate.php
  - vendor/bin/phpunit
