language: php
php:
  - '7.4snapshot'

addons:
  postgresql: "11.4"

env:
  global:
    - DB_HOST=postgres
    - DB_NAME=ussr_poker
    - DB_USER=ussr_poker
    - DB_PASS=secret
    - DB_PORT=5432

before_install:
  - psql -c "CREATE DATABASE ussr_poker;" -U postgres
  - psql -c "CREATE USER ussr_poker WITH PASSWORD 'secret';" -U postgres

install:
  - printf "\n" | pecl install swoole
  - composer install

test:
  - php migrate.php
  - vendor/bin/phpunit
